markdown: redcarpet

pygments: true

redcarpet:
  extensions: ["tables"]

include: [ "_base", "_firebug", "_loader.js", "_utils.js" ]

excerpt_separator: <!--more-->
paginate: 4
paginate_path: "blog/page:num"

authors:
    cjolif:
        name: Christophe Jolif
        url: https://github.com/cjolif
        gravatar: ca9800fc6cacd919e7dbef9676e2c5f1
    AdrianVasiliu:
        name: Adrian Vasiliu
        url: https://github.com/AdrianVasiliu
        gravatar: 3fcefe4617c2bd6677f165b732e8ff81

name: delite, deliteful & co blog
description: All about our journey building delite, deliteful and other JavaScript Front End Open Source projects
url: http://ibm-js.github.io

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
